import 'react';
import HomePageThemeCustomization from '/themes/HomePageTheme';
import Navigation from './_layout/Navigation';
import Footer from './_layout/Footer';
// Keep the titles up to 50-60 characters long
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   keywords : "keyyyyyyyyyyyy",
// }
export default function HomeLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <link rel="icon" href="/favicon.svg" />
          <title>10 Most Important Meta Tags You Need to Know for SEO</title>
          <meta name="title" content="Hydra React Dashboard" />
          <meta
            name="description"
            content="Hydra is a free, super flexible and customizable react redux dashboard template built using MUI React components with open source MIT license."
          />
          <meta
            name="keywords"
            content="react dashboard, react admin, react redux dashboard, ant design template, saas admin, free react dashboard"
          />
          {/* <!-- Open Graph / Facebook --> */}
          <meta property="og:locale" content="en_US" />
          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://Hydradashboard.io/" />
          <meta property="og:site_name" content="Hydradashboard.io" />
          <meta property="article:publisher" content="https://www.facebook.com/codedthemes" />
          <meta property="og:title" content="Hydra React Dashboard | Open Source Admin Template" />
          <meta
            property="og:description"
            content="Hydra is a free, super flexible and customizable react redux dashboard template built using MUI React components with open source MIT license."
          />
          <meta property="og:image" content="https://Hydradashboard.io/adv-banner-images/og-social.png" />
          {/* <!-- Twitter --> */}
          <meta property="twitter:card" content="summary_large_image" />
          <meta property="twitter:url" content="https://Hydradashboard.io" />
          <meta property="twitter:title" content="Hydra React Dashboard | Open Source Admin Template" />
          <meta
            property="twitter:description"
            content="Hydra is a free, super flexible and customizable react redux dashboard template built using MUI React components with open source MIT license."
          />
          <meta property="twitter:image" content="https://Hydradashboard.io/adv-banner-images/og-social.png" />
          <meta name="twitter:creator" content="@codedthemes" />
          <script type="module" src="https://unpkg.com/@splinetool/viewer@0.9.518/build/spline-viewer.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/hls.js@1"></script>
        </head>
        <body>
          <link rel="apple-touch-icon" href="/images/apple-touch-icon.png" />
          <HomePageThemeCustomization>
            <Navigation sx={{ xIndex: 999999999, position: 'relative' }} />
            {children}
            <Footer />
          </HomePageThemeCustomization>
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap&family=Gloock:wght@400;500;600;700"
            rel="stylesheet"
          />
          <link href="/css/customStyle/homePage.css" rel="stylesheet" />
        </body>
      </html>
    </>
  );
}
